"""Add greeting field

Revision ID: 378e9de47a36
Revises: eb8c1364bbc0
Create Date: 2021-11-29 20:45:44.237088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378e9de47a36'
down_revision = 'eb8c1364bbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('greeting', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_data_greeting'), 'data', ['greeting'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_greeting'), table_name='data')
    op.drop_column('data', 'greeting')
    # ### end Alembic commands ###
