"""Initial migration.

Revision ID: eb8c1364bbc0
Revises: 
Create Date: 2021-11-29 17:10:00.889835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import ProgrammingError


# revision identifiers, used by Alembic.
revision = 'eb8c1364bbc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('notes', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_data_notes'), 'data', ['notes'], unique=False)
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_notes'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
